import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
# TERM = "xterm-256color"

[window]
# opacity = 0.95

[font]
size = 12
offset.x = 0
offset.y = 0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
