import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
# TERM = "xterm-256color"

[window]
opacity = 0.95

[font]
size = 13.9
offset.x = 0
offset.y = 0

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Medium"
