#!/bin/sh

TOOLCHAIN=/usr/lib/musl
SYSROOT=/usr/lib/musl

CLANG="clang"

if [ "$0" = "musl-clang++" ]; then
  CLANG="clang++"
fi

$CLANG -target x86_64-unknown-linux-musl --sysroot=$SYSROOT -isystem=$TOOLCHAIN/include -L$TOOLCHAIN/lib "$@"
