#!/bin/sh

TOOLCHAIN=/usr/local/opt/x86_64-unknown-linux-musl/toolchain
SYSROOT=/usr/local/opt/x86_64-unknown-linux-musl/toolchain/x86_64-unknown-linux-musl/sysroot

CLANG="clang"

if [ "$0" = "musl-clang++" ]; then
  CLANG="clang++"
fi

$CLANG -target x86_64-unknown-linux-musl --sysroot=$SYSROOT --gcc-toolchain=$TOOLCHAIN "$@"
